export const brandCopy = {
  maintenance: {
    eyebrow: 'Mantenimiento / desarrollo',
    title: 'La tienda está',
    accent: 'en construcción.',
    description: 'Estamos terminando la colección y preparando la información comercial. Hydross volverá cuando esté lista.',
    statusLabel: 'Estado actual',
    status: 'Acceso temporalmente cerrado',
    note: 'La aplicación continúa en desarrollo.',
  },
  navigation: {
    shop: 'Tienda',
    finder: 'Encuentra lo que necesitas',
    essence: 'Sobre Hydross',
  },
  home: {
    eyebrow: 'Hydross skincare',
    title: 'Cuidado claro,\npara cada día.',
    description: 'Productos para limpiar, hidratar y proteger. Esta es la primera colección visual de Hydross.',
    cta: 'Ver productos',
    marquee: 'LIMPIEZA ✦ HIDRATACIÓN ✦ SÉRUMS ✦ PROTECCIÓN ✦ LIMPIEZA ✦ HIDRATACIÓN ✦',
    introEyebrow: 'Una selección breve',
    introTitle: 'Cuidado\nsin ruido.',
    introDescription: 'La tienda reúne cuatro categorías para explorar la dirección de Hydross mientras la información de producto toma forma.',
    collectionEyebrow: 'La colección',
    collectionTitle: 'Los productos',
    collectionDescription: 'Una primera selección para explorar la marca.',
    essenceEyebrow: '02 / Sobre Hydross',
    essenceTitle: 'Productos claros.\nSin exceso.',
    essenceDescription: 'Hydross comienza con una selección de cuidado facial y una identidad todavía en construcción. Aquí importa que cada cosa tenga un lugar.',
    concernsEyebrow: 'Explora por categoría',
    concernsTitle: '¿Qué estás buscando?',
    concernsDescription: 'Elige una categoría para ver los conceptos disponibles.',
    finderEyebrow: '03 / Encuentra lo que necesitas',
    finderTitle: 'Empieza por\nlo que buscas.',
    finderDescription: 'Responde tres preguntas y revisa una selección inicial, sin diagnósticos ni promesas.',
    finderCta: 'Empezar',
    editorialEyebrow: 'Hydross skincare',
    editorialTitle: 'Una colección en\nconstrucción.',
    editorialDescription: 'Los productos, precios e información que aparecen aquí son material de muestra para validar la dirección de la tienda.',
  },
  finder: {
    progress: 'encuentra lo que necesitas',
    questions: [
      { eyebrow: '01 / 03', title: '¿Qué categoría\nte interesa?', options: ['Limpieza', 'Hidratación', 'Sérums', 'Protección'] },
      { eyebrow: '02 / 03', title: '¿Qué textura\nprefieres explorar?', options: ['Gel o bruma', 'Crema o bálsamo', 'Sérum o aceite', 'Todavía no lo sé'] },
      { eyebrow: '03 / 03', title: '¿Cuánta información\nquieres ver?', options: ['Información breve', 'Quiero comparar', 'Quiero leer todo'] },
    ],
    resultEyebrow: 'Tu selección inicial',
    resultTitle: 'Empieza por\naquí.',
    resultDescription: 'Estos conceptos sirven para mostrar cómo podría organizarse la colección. La información comercial final está pendiente.',
    addCta: 'Agregar selección',
    restartCta: 'Volver a empezar',
  },
  cart: {
    eyebrow: 'Lo que elegiste',
    title: 'Una selección\npara revisar.',
    emptyTitle: 'Aún no has elegido nada.',
    emptyDescription: 'Explora los conceptos disponibles y agrega los que quieras revisar.',
    summary: 'Resumen de muestra',
    total: 'Total de muestra',
    checkout: 'Continuar',
  },
  checkout: {
    eyebrow: 'Compra de muestra',
    title: 'Revisa la selección\nantes de continuar.',
    details: 'Datos de contacto',
    payment: 'Demostración visual — no se realizará ningún cargo.',
    submit: 'Confirmar selección',
    successEyebrow: 'Demostración completada',
    successTitle: 'Selección\nconfirmada.',
    successDescription: 'Esta pantalla representa el cierre del flujo. Los datos comerciales reales se agregarán más adelante.',
  },
  footer: {
    kicker: 'Hydross skincare',
    title: 'Cuidado\ncon criterio.',
    explore: 'Explorar',
    information: 'Información',
    note: 'La primera colección de Hydross está tomando forma.',
  },
} as const
