import { useMemo, useState } from 'react'
import { ArrowDown, ArrowRight, ArrowUpRight, Check, ChevronDown, ChevronLeft, Minus, Plus, Sparkles } from 'lucide-react'
import { Link, Route, Routes, useNavigate, useParams, useSearchParams } from 'react-router-dom'
import { BottleVisual } from './components/BottleVisual'
import { Footer } from './components/Footer'
import { ProductCard } from './components/ProductCard'
import { SiteHeader } from './components/SiteHeader'
import { brandCopy } from './content/brandCopy'
import { categories, formatPrice, getProduct, products, type ProductCategory } from './data/products'
import { useCart } from './store/cart'

function splitLines(value: string) {
  return value.split('\n').map((line) => <span key={line}>{line}<br /></span>)
}

function SectionTitle({ eyebrow, title, copy, align = 'left' }: { eyebrow: string; title: string; copy?: string; align?: 'left' | 'center' }) {
  return <div className={`section-title align-${align}`}><p className="eyebrow">{eyebrow}</p><h2>{splitLines(title)}</h2>{copy && <p className="section-copy">{copy}</p>}</div>
}

function Home() {
  const featured = products.filter((product) => product.featured)
  return <>
    <main>
      <section className="hero section-dark"><div className="hero-grain" /><div className="hero-copy"><p className="eyebrow hero-eyebrow">{brandCopy.home.eyebrow}</p><h1>{splitLines(brandCopy.home.title)}</h1><p className="hero-text">{brandCopy.home.description}</p><Link className="button button-pink" to="/shop">{brandCopy.home.cta} <ArrowRight size={16} /></Link></div><div className="hero-stage"><div className="hero-sun" /><div className="hero-bottle hero-bottle-back"><BottleVisual product={products[2]} large /></div><div className="hero-bottle hero-bottle-front"><BottleVisual product={products[1]} large /></div><div className="hero-caption"><span>01 — {String(products.length).padStart(2, '0')}</span><span>colección inicial</span></div></div><div className="hero-scroll"><ArrowDown size={14} /> explorar</div></section>
      <section className="marquee"><div>{brandCopy.home.marquee}</div></section>
      <section className="intro section-pad"><div className="intro-number">01<span>/04</span></div><div className="intro-copy"><p className="eyebrow">{brandCopy.home.introEyebrow}</p><h2>{splitLines(brandCopy.home.introTitle)}</h2></div><div className="intro-body"><p>{brandCopy.home.introDescription}</p><Link className="text-link" to="/#essence">{brandCopy.navigation.essence} <ArrowRight size={15} /></Link></div></section>
      <section className="shop-preview section-pad"><div className="section-heading-row"><SectionTitle eyebrow={brandCopy.home.collectionEyebrow} title={brandCopy.home.collectionTitle} copy={brandCopy.home.collectionDescription} /><Link className="text-link hide-mobile" to="/shop">Ver la colección <ArrowRight size={15} /></Link></div><div className="product-grid">{featured.map((product) => <ProductCard key={product.id} product={product} />)}</div><Link className="text-link mobile-only" to="/shop">Ver la colección <ArrowRight size={15} /></Link></section>
      <section id="essence" className="essence-section section-dark"><div className="essence-visual"><div className="essence-ring ring-one" /><div className="essence-ring ring-two" /><div className="essence-orb"><span>h.</span></div><span className="essence-caption">hydross<br />skincare</span></div><div className="essence-copy"><p className="eyebrow">{brandCopy.home.essenceEyebrow}</p><h2>{splitLines(brandCopy.home.essenceTitle)}</h2><p>{brandCopy.home.essenceDescription}</p><Link className="button button-outline" to="/find">{brandCopy.navigation.finder} <ArrowRight size={16} /></Link></div></section>
      <section className="concerns section-pad"><SectionTitle eyebrow={brandCopy.home.concernsEyebrow} title={brandCopy.home.concernsTitle} copy={brandCopy.home.concernsDescription} align="center" /><div className="concern-grid"><Link to="/shop?category=Hidratación" className="concern-card concern-pink"><span>01</span><h3>Explorar<br /><em>hidratación</em></h3><ArrowUpRight /></Link><Link to="/shop?category=Sérums" className="concern-card concern-cream"><span>02</span><h3>Explorar<br /><em>sérums</em></h3><ArrowUpRight /></Link><Link to="/shop?category=Limpieza" className="concern-card concern-black"><span>03</span><h3>Explorar<br /><em>limpieza</em></h3><ArrowUpRight /></Link></div></section>
      <section className="ritual-teaser section-pad"><div className="ritual-teaser-copy"><p className="eyebrow">{brandCopy.home.finderEyebrow}</p><h2>{splitLines(brandCopy.home.finderTitle)}</h2><p>{brandCopy.home.finderDescription}</p><Link className="button button-dark" to="/find">{brandCopy.home.finderCta} <ArrowRight size={16} /></Link></div><div className="ritual-stack"><div className="stack-card stack-back"><span>lo que buscas</span><strong>elige</strong></div><div className="stack-card stack-front"><span>hydross / selección</span><strong>empieza</strong><Sparkles /></div></div></section>
      <section className="quote-section section-dark"><p className="quote-mark">h.</p><blockquote>{splitLines(brandCopy.home.editorialTitle)}</blockquote><p className="quote-by">{brandCopy.home.editorialDescription}</p></section>
    </main><Footer />
  </>
}

function Shop() {
  const [searchParams] = useSearchParams()
  const [category, setCategory] = useState<string>(searchParams.get('category') ?? 'Todos')
  const [query, setQuery] = useState('')
  const filtered = useMemo(() => products.filter((product) => (category === 'Todos' || product.category === category) && (!query || `${product.name} ${product.description}`.toLowerCase().includes(query.toLowerCase()))), [category, query])
  return <><main className="shop-page"><section className="shop-hero section-dark"><div><p className="eyebrow">Hydross skincare</p><h1>Explora la<br /><em>colección.</em></h1></div><p>Una primera selección de conceptos para definir la dirección de Hydross.</p></section><section className="catalog section-pad"><div className="catalog-toolbar"><div className="category-tabs">{categories.map((item) => <button key={item.value} className={category === item.value ? 'active' : ''} onClick={() => setCategory(item.value)}>{item.label}</button>)}</div><label className="catalog-search">Buscar <input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="nombre o categoría" /></label></div><div className="catalog-result-row"><p>{filtered.length} conceptos</p><button className="sort-button">Orden original <ChevronDown size={15} /></button></div>{filtered.length ? <div className="product-grid">{filtered.map((product) => <ProductCard key={product.id} product={product} />)}</div> : <div className="empty-state"><p className="eyebrow">Sin coincidencias</p><h2>Prueba otra palabra.</h2><button className="button button-dark" onClick={() => { setQuery(''); setCategory('Todos') }}>Ver todo</button></div>}</section></main><Footer /></>
}

function ProductPage() {
  const { slug = '' } = useParams(); const product = getProduct(slug); const addItem = useCart((state) => state.addItem); const navigate = useNavigate(); const [added, setAdded] = useState(false); const [open, setOpen] = useState('about')
  if (!product) return <NotFound />
  const related = products.filter((item) => item.id !== product.id && item.category === product.category).slice(0, 3)
  const handleAdd = () => { addItem(product); setAdded(true); window.setTimeout(() => setAdded(false), 1800) }
  return <><main className="product-page"><div className="breadcrumb"><Link to="/shop">Tienda</Link><ChevronLeft size={13} /><span>{product.name}</span></div><section className="product-detail section-pad"><div className="product-detail-visual"><BottleVisual product={product} large /></div><div className="product-detail-copy"><p className="eyebrow">{product.category} · {product.size}</p><h1>{product.name}</h1><p className="detail-price"><span>Precio de muestra</span>{formatPrice(product.priceMXN)}</p><p className="concept-status">Concepto visual · información comercial pendiente</p><p className="detail-description">{product.description}</p><div className="detail-accordions"><div className="accordion"><button onClick={() => setOpen(open === 'about' ? '' : 'about')}><span>Sobre este concepto</span>{open === 'about' ? <Minus size={16} /> : <Plus size={16} />}</button>{open === 'about' && <p>{product.description} El nombre, el formato y el precio se muestran únicamente para validar la experiencia de tienda.</p>}</div><div className="accordion"><button onClick={() => setOpen(open === 'format' ? '' : 'format')}><span>Ficha de presentación</span>{open === 'format' ? <Minus size={16} /> : <Plus size={16} />}</button>{open === 'format' && <p>Categoría: {product.category}. Presentación: {product.size}. La información final del producto se agregará cuando la colección esté confirmada.</p>}</div></div><button className={`button add-button ${added ? 'added' : ''}`} onClick={handleAdd}>{added ? <><Check size={17} /> Agregado</> : <>Agregar selección <Plus size={17} /></>}</button><button className="continue-shopping" onClick={() => navigate('/shop')}>← Seguir explorando</button></div></section><section className="related section-pad"><SectionTitle eyebrow="Más conceptos" title="De la misma categoría" /><div className="product-grid">{related.map((item) => <ProductCard key={item.id} product={item} />)}</div></section></main><Footer /></>
}

function Finder() {
  const [step, setStep] = useState(0); const [answers, setAnswers] = useState<string[]>([]); const navigate = useNavigate(); const questions = brandCopy.finder.questions
  const current = questions[step]
  const selectedCategory = answers[0] as ProductCategory | undefined
  const result = selectedCategory && ['Limpieza', 'Hidratación', 'Sérums', 'Protección'].includes(selectedCategory) ? products.filter((product) => product.category === selectedCategory).slice(0, 2) : products.slice(0, 2)
  if (step === questions.length) return <main className="ritual-page ritual-result section-dark"><div className="ritual-result-content"><p className="eyebrow">{brandCopy.finder.resultEyebrow}</p><h1>{splitLines(brandCopy.finder.resultTitle)}</h1><p>{brandCopy.finder.resultDescription}</p><div className="result-products">{result.map((product) => <div key={product.id} className="result-product"><BottleVisual product={product} /><div><p className="eyebrow">{product.category}</p><h3>{product.name}</h3><span>Precio de muestra · {formatPrice(product.priceMXN)}</span></div></div>)}</div><div className="result-actions"><button className="button button-pink" onClick={() => result.forEach((product) => useCart.getState().addItem(product))}>{brandCopy.finder.addCta} <ArrowRight size={16} /></button><button className="text-link light" onClick={() => { setStep(0); setAnswers([]) }}>{brandCopy.finder.restartCta} <ArrowRight size={15} /></button></div></div></main>
  return <main className="ritual-page"><div className="ritual-progress"><span>{brandCopy.finder.progress}</span><span>{current.eyebrow}</span></div><div className="ritual-question"><div className="ritual-question-copy"><p className="eyebrow">{current.eyebrow}</p><h1>{splitLines(current.title)}</h1><p>Una selección inicial, sin diagnósticos ni promesas.</p></div><div className="ritual-options">{current.options.map((option, index) => <button key={option} onClick={() => { setAnswers((currentAnswers) => [...currentAnswers, option]); setStep((currentStep) => currentStep + 1) }}><span>0{index + 1}</span>{option}<ArrowRight size={17} /></button>)}</div></div><div className="ritual-footer"><button className="text-link" onClick={() => step > 0 ? setStep((currentStep) => currentStep - 1) : navigate('/')}>{step > 0 ? '← Anterior' : '← Inicio'}</button><span>hydross<span className="pink-dot">.</span></span></div></main>
}

function Cart() {
  const { items, updateQuantity, removeItem, subtotal } = useCart(); const navigate = useNavigate(); const total = subtotal()
  return <><main className="cart-page section-pad"><div className="cart-heading"><div><p className="eyebrow">{brandCopy.cart.eyebrow}</p><h1>{splitLines(brandCopy.cart.title)}</h1></div><Link className="text-link" to="/shop">Seguir explorando <ArrowRight size={15} /></Link></div>{items.length === 0 ? <div className="empty-cart"><div className="empty-orb">✦</div><h2>{brandCopy.cart.emptyTitle}</h2><p>{brandCopy.cart.emptyDescription}</p><Link className="button button-dark" to="/shop">Explorar productos</Link></div> : <div className="cart-layout"><div className="cart-lines">{items.map(({ product, quantity }) => <div className="cart-line" key={product.id}><BottleVisual product={product} /><div className="cart-line-info"><Link to={`/product/${product.slug}`}>{product.name}</Link><p>{product.size} · {product.category}</p><button onClick={() => removeItem(product.id)}>Eliminar</button></div><div className="quantity"><button onClick={() => updateQuantity(product.id, quantity - 1)}><Minus size={14} /></button><span>{quantity}</span><button onClick={() => updateQuantity(product.id, quantity + 1)}><Plus size={14} /></button></div><strong>{formatPrice(product.priceMXN * quantity)}</strong></div>)}</div><aside className="summary"><p className="eyebrow">{brandCopy.cart.summary}</p><div className="summary-total"><span>{brandCopy.cart.total}</span><strong>{formatPrice(total)}</strong></div><button className="button button-dark" onClick={() => navigate('/checkout')}>{brandCopy.cart.checkout} <ArrowRight size={16} /></button><p className="summary-note">Importes de demostración · sin cargo</p></aside></div>}</main><Footer /></>
}

function Checkout() { const { items, subtotal, clear } = useCart(); const [done, setDone] = useState(false); const total = subtotal(); if (done) return <NavigateSuccess />; if (!items.length) return <NavigateEmpty />; return <main className="checkout-page section-pad"><div className="checkout-heading"><Link to="/cart"><ChevronLeft size={15} /> Selección</Link><p className="eyebrow">{brandCopy.checkout.eyebrow}</p><h1>{splitLines(brandCopy.checkout.title)}</h1></div><div className="checkout-layout"><form className="checkout-form" onSubmit={(event) => { event.preventDefault(); clear(); setDone(true) }}><div className="form-section"><h2>{brandCopy.checkout.details}</h2><div className="form-grid"><label>Nombre completo<input required placeholder="Nombre" /></label><label>Correo electrónico<input required type="email" placeholder="correo@ejemplo.com" /></label><label className="full">Dirección<input required placeholder="Calle y número" /></label><label>Ciudad<input required placeholder="Ciudad" /></label><label>Código postal<input required pattern="[0-9]{5}" placeholder="00000" /></label></div></div><div className="form-section"><h2>Pago</h2><div className="demo-payment"><Sparkles size={17} /><span>{brandCopy.checkout.payment}</span></div></div><button className="button button-dark checkout-submit">{brandCopy.checkout.submit} <ArrowRight size={16} /></button></form><aside className="checkout-order"><p className="eyebrow">{brandCopy.cart.summary}</p>{items.map(({ product, quantity }) => <div className="checkout-item" key={product.id}><span>{quantity} × {product.name}</span><strong>{formatPrice(product.priceMXN * quantity)}</strong></div>)}<div className="summary-total"><span>{brandCopy.cart.total}</span><strong>{formatPrice(total)}</strong></div></aside></div></main> }

function NavigateSuccess() { return <main className="success-page section-dark"><div className="success-icon"><Check size={25} /></div><p className="eyebrow">{brandCopy.checkout.successEyebrow}</p><h1>{splitLines(brandCopy.checkout.successTitle)}</h1><p>{brandCopy.checkout.successDescription}</p><Link className="button button-pink" to="/shop">Volver a la colección <ArrowRight size={16} /></Link></main> }
function NavigateEmpty() { return <main className="empty-cart section-pad"><div className="empty-orb">✦</div><h2>La selección está vacía.</h2><Link className="button button-dark" to="/shop">Explorar productos</Link></main> }
function NotFound() { return <main className="empty-cart section-pad"><p className="eyebrow">404</p><h2>Esta página no existe.</h2><Link className="button button-dark" to="/">Volver al inicio</Link></main> }

function App() { return <><SiteHeader /><Routes><Route path="/" element={<Home />} /><Route path="/shop" element={<Shop />} /><Route path="/product/:slug" element={<ProductPage />} /><Route path="/find" element={<Finder />} /><Route path="/cart" element={<Cart />} /><Route path="/checkout" element={<Checkout />} /><Route path="*" element={<NotFound />} /></Routes></> }

export default App
