import { useMemo, useState } from 'react'
import { ArrowDown, ArrowRight, ArrowUpRight, Check, ChevronDown, ChevronLeft, Minus, Plus, ShieldCheck, Sparkles, Truck } from 'lucide-react'
import { Link, Route, Routes, useNavigate, useParams, useSearchParams } from 'react-router-dom'
import { BottleVisual } from './components/BottleVisual'
import { Footer } from './components/Footer'
import { ProductCard } from './components/ProductCard'
import { SiteHeader } from './components/SiteHeader'
import { categories, formatPrice, getProduct, products, type Product } from './data/products'
import { useCart } from './store/cart'

function SectionTitle({ eyebrow, title, copy, align = 'left' }: { eyebrow: string; title: string; copy?: string; align?: 'left' | 'center' }) {
  return <div className={`section-title align-${align}`}><p className="eyebrow">{eyebrow}</p><h2>{title}</h2>{copy && <p className="section-copy">{copy}</p>}</div>
}

function Home() {
  const featured = products.filter((product) => product.featured)
  return <>
    <main>
      <section className="hero section-dark"><div className="hero-grain" /><div className="hero-copy"><p className="eyebrow hero-eyebrow">Skincare para sentirte en tu piel</p><h1>Tu piel,<br /><em>en su mejor mood.</em></h1><p className="hero-text">Fórmulas sensoriales, ingredientes que sí hacen match y rituales que caben en tu vida real.</p><Link className="button button-pink" to="/shop">Conoce el ritual <ArrowRight size={16} /></Link></div><div className="hero-stage"><div className="hero-sticker">desde<br /><strong>2020</strong></div><div className="hero-sun" /><div className="hero-bottle hero-bottle-back"><BottleVisual product={products[2]} large /></div><div className="hero-bottle hero-bottle-front"><BottleVisual product={products[1]} large /></div><div className="hero-caption"><span>01 — 09</span><span>una colección para tu glow diario</span></div></div><div className="hero-scroll"><ArrowDown size={14} /> scroll to glow</div></section>
      <section className="marquee"><div>PRODUCTO MEXICANO <span>✦</span> TECNOLOGÍA FRANCESA <span>✦</span> VEGANA <span>✦</span> SIN COMPLICACIONES <span>✦</span> PRODUCTO MEXICANO <span>✦</span></div></section>
      <section className="intro section-pad"><div className="intro-number">01<span>/04</span></div><div className="intro-copy"><p className="eyebrow">El mood</p><h2>Skincare que<br /><em>se siente bien.</em></h2></div><div className="intro-body"><p>Creemos que cuidar tu piel no debería sentirse como tarea. Hydross combina activos efectivos con texturas que dan ganas de usar todos los días.</p><Link className="text-link" to="/#essence">Conoce nuestra esencia <ArrowRight size={15} /></Link></div></section>
      <section className="shop-preview section-pad"><div className="section-heading-row"><SectionTitle eyebrow="La colección" title="Tus nuevos favoritos" copy="Pocos pasos. Buenos ingredientes. Mucho glow." /><Link className="text-link hide-mobile" to="/shop">Ver toda la tienda <ArrowRight size={15} /></Link></div><div className="product-grid">{featured.map((product) => <ProductCard key={product.id} product={product} />)}</div><Link className="text-link mobile-only" to="/shop">Ver toda la tienda <ArrowRight size={15} /></Link></section>
      <section id="essence" className="essence-section section-dark"><div className="essence-visual"><div className="essence-ring ring-one" /><div className="essence-ring ring-two" /><div className="essence-orb"><span>h.</span></div><span className="essence-caption">the hydross<br />state of mind</span></div><div className="essence-copy"><p className="eyebrow">02 / Nuestra esencia</p><h2>Menos ruido.<br /><em>Más ritual.</em></h2><p>Productos sensoriales, efectivos y honestos. Diseñados en México, inspirados por el cuidado francés y hechos para convertirse en tu momento favorito del día.</p><Link className="button button-outline" to="/ritual">Encuentra tu ritual <ArrowRight size={16} /></Link></div></section>
      <section className="concerns section-pad"><SectionTitle eyebrow="Tu piel habla" title="Empecemos por lo que necesita" copy="Elige tu mood de piel y descubre dónde empezar." align="center" /><div className="concern-grid"><Link to="/shop?concern=Deshidratación" className="concern-card concern-pink"><span>01</span><h3>Necesito<br /><em>hidratación</em></h3><ArrowUpRight /></Link><Link to="/shop?concern=Opacidad" className="concern-card concern-cream"><span>02</span><h3>Quiero más<br /><em>luminosidad</em></h3><ArrowUpRight /></Link><Link to="/shop?concern=Textura" className="concern-card concern-black"><span>03</span><h3>Quiero una piel<br /><em>más suave</em></h3><ArrowUpRight /></Link></div></section>
      <section className="ritual-teaser section-pad"><div className="ritual-teaser-copy"><p className="eyebrow">03 / El ritual</p><h2>Tu piel no necesita<br /><em>más pasos.</em></h2><p>Solo los correctos. Responde tres preguntas y armamos una rutina que sí va contigo.</p><Link className="button button-dark" to="/ritual">Armar mi ritual <ArrowRight size={16} /></Link></div><div className="ritual-stack"><div className="stack-card stack-back"><span>tu piel</span><strong>tu ritmo</strong></div><div className="stack-card stack-front"><span>the everyday</span><strong>ritual</strong><Sparkles /></div></div></section>
      <section className="quote-section section-dark"><p className="quote-mark">“</p><blockquote>Mi piel se siente como yo: <em>viva, suave y un poquito extra.</em></blockquote><p className="quote-by">— una hydross girl</p></section>
    </main><Footer />
  </>
}

function Shop() {
  const [searchParams] = useSearchParams()
  const [category, setCategory] = useState<string>(searchParams.get('category') ?? 'Todos')
  const [concern, setConcern] = useState<string>(searchParams.get('concern') ?? 'Todos')
  const [query, setQuery] = useState('')
  const filtered = useMemo(() => products.filter((product) => (category === 'Todos' || product.category === category) && (concern === 'Todos' || product.concerns.includes(concern)) && (!query || `${product.name} ${product.description} ${product.concerns.join(' ')}`.toLowerCase().includes(query.toLowerCase()))), [category, concern, query])
  return <><main className="shop-page"><section className="shop-hero section-dark"><div><p className="eyebrow">La colección hydross.</p><h1>Todo lo que tu piel<br /><em>quería probar.</em></h1></div><p>Fórmulas sensoriales para limpiar, hidratar, iluminar y proteger. Elige tu próximo ritual.</p></section><section className="catalog section-pad"><div className="catalog-toolbar"><div className="category-tabs">{categories.map((item) => <button key={item.value} className={category === item.value ? 'active' : ''} onClick={() => setCategory(item.value)}>{item.label}</button>)}</div><label className="catalog-search">Buscar <input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="un sérum, una crema..." /></label></div><div className="catalog-result-row"><p>{filtered.length} productos{concern !== 'Todos' && <button className="active-filter" onClick={() => setConcern('Todos')}> · {concern} ×</button>}</p><button className="sort-button">Más relevantes <ChevronDown size={15} /></button></div>{filtered.length ? <div className="product-grid">{filtered.map((product) => <ProductCard key={product.id} product={product} />)}</div> : <div className="empty-state"><p className="eyebrow">No encontramos ese mood</p><h2>Prueba con otra búsqueda.</h2><button className="button button-dark" onClick={() => { setQuery(''); setConcern('Todos'); setCategory('Todos') }}>Ver todos</button></div>}</section></main><Footer /></>
}

function ProductPage() {
  const { slug = '' } = useParams(); const product = getProduct(slug); const addItem = useCart((state) => state.addItem); const navigate = useNavigate(); const [added, setAdded] = useState(false); const [open, setOpen] = useState('benefits')
  if (!product) return <NotFound />
  const related = products.filter((item) => item.id !== product.id && item.category === product.category).slice(0, 3)
  const handleAdd = () => { addItem(product); setAdded(true); window.setTimeout(() => setAdded(false), 1800) }
  return <><main className="product-page"><div className="breadcrumb"><Link to="/shop">Tienda</Link><ChevronLeft size={13} /><span>{product.name}</span></div><section className="product-detail section-pad"><div className="product-detail-visual"><BottleVisual product={product} large /><span className="detail-note">concept visual<br />replace with product photo</span></div><div className="product-detail-copy"><p className="eyebrow">{product.category} · {product.size}</p><h1>{product.name}</h1><p className="detail-price">{formatPrice(product.priceMXN)}</p><p className="detail-description">{product.description}</p><div className="detail-pills">{product.benefits.map((benefit) => <span key={benefit}>{benefit}</span>)}</div><div className="detail-accordions">{[['benefits', 'Por qué te va a encantar', product.benefits.join(' · ')], ['ingredients', 'Ingredientes clave', product.ingredients.join(' · ')], ['howto', 'Cómo usarlo', product.howToUse]].map(([key, title, content]) => <div className="accordion" key={key}><button onClick={() => setOpen(open === key ? '' : key)}><span>{title}</span>{open === key ? <Minus size={16} /> : <Plus size={16} />}</button>{open === key && <p>{content}</p>}</div>)}</div><button className={`button add-button ${added ? 'added' : ''}`} onClick={handleAdd}>{added ? <><Check size={17} /> Agregado a tu ritual</> : <>Agregar al carrito <Plus size={17} /></>}</button><button className="continue-shopping" onClick={() => navigate('/shop')}>← Seguir explorando</button><div className="shipping-promise"><span><Truck size={17} /> Envío gratis +$899</span><span><ShieldCheck size={17} /> Compra segura</span></div></div></section><section className="related section-pad"><SectionTitle eyebrow="Completa el ritual" title="También te puede gustar" /><div className="product-grid">{related.map((item) => <ProductCard key={item.id} product={item} />)}</div></section></main><Footer /></>
}

function Ritual() {
  const [step, setStep] = useState(0); const [answers, setAnswers] = useState<string[]>([]); const navigate = useNavigate()
  const questions = [{ eyebrow: '01 / 03', title: '¿Cómo se siente tu piel\nla mayoría de los días?', options: ['Tirante y con sed', 'Brilla en la zona T', 'Reactiva y delicada', 'Bastante equilibrada'] }, { eyebrow: '02 / 03', title: '¿Qué te gustaría ver\nen el espejo?', options: ['Más hidratación', 'Más luminosidad', 'Textura más suave', 'Una barrera más fuerte'] }, { eyebrow: '03 / 03', title: '¿Cuánto tiempo tienes\npara tu ritual?', options: ['Solo lo esencial', 'Tengo 5 minutos', 'Quiero disfrutarlo'] }]
  const current = questions[step]; const result = answers[0] === 'Tirante y con sed' ? [getProduct('crema-nube'), getProduct('serum-luz')] : answers[1] === 'Más luminosidad' ? [getProduct('serum-luz'), getProduct('protector-diario')] : [getProduct('gel-de-agua'), getProduct('crema-nube')]
  if (step === 3) return <main className="ritual-page ritual-result section-dark"><div className="ritual-result-content"><p className="eyebrow">Tu ritual hydross</p><h1>Tu piel pide<br /><em>un poco de esto.</em></h1><p>Una rutina simple, sensorial y pensada para acompañarte sin complicarte.</p><div className="result-products">{result.map((product) => product && <div key={product.id} className="result-product"><BottleVisual product={product} /><div><p className="eyebrow">{product.category}</p><h3>{product.name}</h3><span>{formatPrice(product.priceMXN)}</span></div></div>)}</div><div className="result-actions"><button className="button button-pink" onClick={() => result.forEach((product) => product && useCart.getState().addItem(product))}>Agregar mi ritual <ArrowRight size={16} /></button><button className="text-link light" onClick={() => { setStep(0); setAnswers([]) }}>Volver a empezar <ArrowRight size={15} /></button></div></div></main>
  return <main className="ritual-page"><div className="ritual-progress"><span>ritual finder</span><span>{current.eyebrow}</span></div><div className="ritual-question"><div className="ritual-question-copy"><p className="eyebrow">{current.eyebrow}</p><h1>{current.title.split('\n').map((line) => <span key={line}>{line}<br /></span>)}</h1><p>Tu respuesta nos ayuda a encontrarte una rutina que se sienta muy tú.</p></div><div className="ritual-options">{current.options.map((option, index) => <button key={option} onClick={() => { setAnswers([...answers, option]); setStep(step + 1) }}><span>0{index + 1}</span>{option}<ArrowRight size={17} /></button>)}</div></div><div className="ritual-footer"><button className="text-link" onClick={() => step > 0 ? setStep(step - 1) : navigate('/')}>{step > 0 ? '← Anterior' : '← Volver al inicio'}</button><span>hydross<span className="pink-dot">.</span></span></div></main>
}

function Cart() {
  const { items, updateQuantity, removeItem, subtotal } = useCart(); const navigate = useNavigate(); const total = subtotal(); const shipping = total >= 899 || total === 0 ? 0 : 89
  return <><main className="cart-page section-pad"><div className="cart-heading"><div><p className="eyebrow">Tu selección</p><h1>Tu ritual<br /><em>empieza aquí.</em></h1></div><Link className="text-link" to="/shop">Seguir comprando <ArrowRight size={15} /></Link></div>{items.length === 0 ? <div className="empty-cart"><div className="empty-orb">✦</div><h2>Tu carrito está tomando aire.</h2><p>Agrega algo bonito para tu piel y volvemos a hablar.</p><Link className="button button-dark" to="/shop">Explorar productos</Link></div> : <div className="cart-layout"><div className="cart-lines">{items.map(({ product, quantity }) => <div className="cart-line" key={product.id}><BottleVisual product={product} /><div className="cart-line-info"><Link to={`/product/${product.slug}`}>{product.name}</Link><p>{product.size} · {product.category}</p><button onClick={() => removeItem(product.id)}>Eliminar</button></div><div className="quantity"><button onClick={() => updateQuantity(product.id, quantity - 1)}><Minus size={14} /></button><span>{quantity}</span><button onClick={() => updateQuantity(product.id, quantity + 1)}><Plus size={14} /></button></div><strong>{formatPrice(product.priceMXN * quantity)}</strong></div>)}</div><aside className="summary"><p className="eyebrow">Resumen</p><div><span>Subtotal</span><strong>{formatPrice(total)}</strong></div><div><span>Envío</span><strong>{shipping === 0 ? 'Gratis' : formatPrice(shipping)}</strong></div><div className="summary-total"><span>Total</span><strong>{formatPrice(total + shipping)}</strong></div><button className="button button-dark" onClick={() => navigate('/checkout')}>Ir al checkout <ArrowRight size={16} /></button><p className="summary-note">✦ Envío gratis a partir de $899</p></aside></div>}</main><Footer /></>
}

function Checkout() { const { items, subtotal, clear } = useCart(); const [done, setDone] = useState(false); const total = subtotal(); if (done) return <NavigateSuccess />; if (!items.length) return <NavigateEmpty />; return <main className="checkout-page section-pad"><div className="checkout-heading"><Link to="/cart"><ChevronLeft size={15} /> Carrito</Link><p className="eyebrow">Checkout seguro</p><h1>Un último paso<br /><em>para tu ritual.</em></h1></div><div className="checkout-layout"><form className="checkout-form" onSubmit={(event) => { event.preventDefault(); clear(); setDone(true) }}><div className="form-section"><h2>Datos de entrega</h2><div className="form-grid"><label>Nombre completo<input required placeholder="Tu nombre" /></label><label>Correo electrónico<input required type="email" placeholder="hola@ejemplo.com" /></label><label className="full">Dirección<input required placeholder="Calle, número y colonia" /></label><label>Ciudad<input required placeholder="Ciudad" /></label><label>Código postal<input required pattern="[0-9]{5}" placeholder="00000" /></label></div></div><div className="form-section"><h2>Forma de pago</h2><div className="demo-payment"><Sparkles size={17} /><span>Demo visual — no se realizará ningún cargo</span></div></div><button className="button button-dark checkout-submit">Confirmar pedido <ArrowRight size={16} /></button></form><aside className="checkout-order"><p className="eyebrow">Tu ritual</p>{items.map(({ product, quantity }) => <div className="checkout-item" key={product.id}><span>{quantity} × {product.name}</span><strong>{formatPrice(product.priceMXN * quantity)}</strong></div>)}<div className="summary-total"><span>Total</span><strong>{formatPrice(total)}</strong></div></aside></div></main> }

function NavigateSuccess() { return <main className="success-page section-dark"><div className="success-icon"><Check size={25} /></div><p className="eyebrow">Pedido recibido</p><h1>Tu ritual ya<br /><em>va en camino.</em></h1><p>Esta es una confirmación de demo. Próximamente aquí vivirá tu experiencia real de compra.</p><Link className="button button-pink" to="/shop">Seguir explorando <ArrowRight size={16} /></Link></main> }
function NavigateEmpty() { return <main className="empty-cart section-pad"><div className="empty-orb">✦</div><h2>Tu carrito está vacío.</h2><Link className="button button-dark" to="/shop">Explorar productos</Link></main> }
function NotFound() { return <main className="empty-cart section-pad"><p className="eyebrow">404</p><h2>Esta página se fue a hacer skincare.</h2><Link className="button button-dark" to="/">Volver al inicio</Link></main> }

function App() { return <><SiteHeader /><Routes><Route path="/" element={<Home />} /><Route path="/shop" element={<Shop />} /><Route path="/product/:slug" element={<ProductPage />} /><Route path="/ritual" element={<Ritual />} /><Route path="/cart" element={<Cart />} /><Route path="/checkout" element={<Checkout />} /><Route path="*" element={<NotFound />} /></Routes></> }

export default App
